name: Beta Release

on:
  release:
    types: [prereleased]

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  CI: true

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup shell
        uses: actions/setup-node@v4
        with:
          node-version: 23

      - name: Get Tag
        uses: olegtarasov/get-tag@v2.1
        id: tagName
        with:
          tagRegex: "(?<package>.*)_(?<version>.*)"

      - name: Install dependencies
        run: |
          corepack enable
          yarn

      - name: Typecheck
        run: yarn workspace @react-beauty/${{ steps.tagName.outputs.package }} check

      - name: Lint
        run: yarn workspace @react-beauty/${{ steps.tagName.outputs.package }} lint
      - name: Bump Version for Standalone
        run: yarn workspace @react-beauty/${{ steps.tagName.outputs.package }} version prerelease

      - name: Bump Version for UI Module
        if: ${{ contains(steps.tagName.outputs.package, 'ui-') }}
        run: |
          yarn workspace @react-beauty/ui version prerelease

      - name: Bump Version for Hook Module
        if: ${{ !contains(steps.tagName.outputs.package, 'ui-') }}
        run: |
          yarn workspace @react-beauty/use version prerelease

      - name: Bump version
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: |
            chore: update  package ${{ steps.tagName.outputs.package }} version
          title: |
            chore: update package ${{ steps.tagName.outputs.package }} version
          branch: package-version-beta/${{ steps.tagName.outputs.package }}
          base: main

      - name: Build
        run: yarn workspace @react-beauty/${{ steps.tagName.outputs.package }} build
      - name: Publish Standalone
        run: |
          yarn workspace @react-beauty/${{ steps.tagName.outputs.package }} version prerelease
          yarn workspace @react-beauty/${{ steps.tagName.outputs.package }} npm publish --tag beta

      - name: Publish UI Module
        if: ${{ contains(steps.tagName.outputs.package, 'ui-') }}
        run: |
          yarn workspace @react-beauty/ui version prerelease
          yarn workspace @react-beauty/ui npm publish --tag beta

      - name: Publish Hook Module
        if: ${{ !contains(steps.tagName.outputs.package, 'ui-') }}
        run: |
          yarn workspace @react-beauty/use version prerelease
          yarn workspace @react-beauty/use npm publish --tag beta
