name: Health Check

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  CI: true

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  health-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup shell
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: |
          corepack enable
          yarn

      - name: Typecheck
        run: yarn workspaces foreach --since --parallel run check

      - name: Lint
        run: yarn workspaces foreach --since --parallel run lint

      - name: Build
        run: yarn workspaces foreach --since --parallel run build
