name: Beta Release

on:
  release:
    types: [released]

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  CI: true

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup shell
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Get Tag
        uses: olegtarasov/get-tag@v2.1
        id: tagName
        with:
          tagRegex: "(?<package>.*)_(?<version>.*)"

      - name: Install dependencies
        run: |
          corepack enable
          yarn

      - name: Typecheck
        run: yarn workspace @react-beauty/${{ steps.tagName.outputs.package }} check

      - name: Lint
        run: yarn workspace @react-beauty/${{ steps.tagName.outputs.package }} lint

      - name: Bump Version for Standalone
        run: yarn workspace @react-beauty/${{ steps.tagName.outputs.package }} version patch

      - name: Bump Version for Interfaces Module
        if: ${{ contains(steps.tagName.outputs.package, 'ui-') && !contains(steps.tagName.outputs.package, 'use-') }}
        run: |
          yarn workspace @react-beauty/interfaces version patch

      - name: Bump Version for Hook Module
        if: ${{ !contains(steps.tagName.outputs.package, 'ui-') && contains(steps.tagName.outputs.package, 'use-') }}
        run: |
          yarn workspace @react-beauty/hooks version patch

      - name: Bump Version for Components Module
        if: ${{ !contains(steps.tagName.outputs.package, 'ui-') && !contains(steps.tagName.outputs.package, 'use-') }}
        run: |
          yarn workspace @react-beauty/components version patch

      - name: Bump version
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: |
            chore: update  package ${{ steps.tagName.outputs.package }} version
          title: |
            chore: update package ${{ steps.tagName.outputs.package }} version
          branch: package-version-beta/${{ steps.tagName.outputs.package }}
          base: main

      - name: Publish Standalone
        run: |
          yarn workspace @react-beauty/${{ steps.tagName.outputs.package }} build
          yarn workspace @react-beauty/${{ steps.tagName.outputs.package }} version patch
          yarn workspace @react-beauty/${{ steps.tagName.outputs.package }} npm publish --tag latest

      - name: Publish Interfaces Module
        if: ${{ contains(steps.tagName.outputs.package, 'ui-') && !contains(steps.tagName.outputs.package, 'use-') }}
        run: |
          yarn workspace @react-beauty/interfaces build
          yarn workspace @react-beauty/interfaces version patch
          yarn workspace @react-beauty/interfaces npm publish --tag latest

      - name: Publish Hooks Module
        if: ${{ !contains(steps.tagName.outputs.package, 'ui-') && contains(steps.tagName.outputs.package, 'use-') }}

        run: |
          yarn workspace @react-beauty/hooks build
          yarn workspace @react-beauty/hooks version patch
          yarn workspace @react-beauty/hooks npm publish --tag latest

      - name: Publish Components Module
        if: ${{ !contains(steps.tagName.outputs.package, 'ui-') && !contains(steps.tagName.outputs.package, 'use-') }}
        run: |
          yarn workspace @react-beauty/components build
          yarn workspace @react-beauty/components version patch
          yarn workspace @react-beauty/components npm publish --tag latest
